From 555fa664e306b27f9db290ef252e8836061501b8 Mon Sep 17 00:00:00 2001
From: GammaC0de <gammac0de@users.noreply.github.com>
Date: Sat, 15 May 2021 04:00:11 +0300
Subject: [PATCH 035/150] fix false "unexpected keyword argument 'thread'"
 error

---
 src/pyload/core/threads/addon_thread.py | 5 +++++
 1 file changed, 5 insertions(+)

--- a/src/pyload/core/threads/addon_thread.py
+++ b/src/pyload/core/threads/addon_thread.py
@@ -45,6 +45,7 @@ class AddonThread(PluginThread):
 
     def run(self):
         try:
+            retry = False
             try:
                 self.kwargs["thread"] = self
                 self.f(*self.args, **self.kwargs)
@@ -52,9 +53,13 @@ class AddonThread(PluginThread):
                 # dirty method to filter out exceptions
                 if "unexpected keyword argument 'thread'" not in exc.args[0]:
                     raise
+                else:
+                    retry = True
 
+            if retry:
                 del self.kwargs["thread"]
                 self.f(*self.args, **self.kwargs)
+
         finally:
             local = copy(self.active)
             for x in local:
